/**
 * Export the OpenAPI document served at /docs to docs/openapi.yaml.
 *
 *   npm run openapi:export              # with the production server URL
 *   npm run openapi:export:local        # relative /api/v1 server only
 *   npx tsx scripts/export-openapi.ts --base=https://cidb-tender-api.onrender.com
 *
 * Does not need a live database connection — the app builds its OpenAPI
 * document from route schemas alone. CI re-runs this and fails when
 * docs/openapi.yaml drifts from the code (see .github/workflows/ci.yml).
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { stringify } from 'yaml';

/** Production origin advertised in the exported document's `servers`. */
const DEFAULT_PUBLIC_BASE_URL = 'https://cidb-tender-api.onrender.com';

function parseBase(argv: string[]): string {
  for (const arg of argv) {
    if (arg === '--relative' || arg === '--base=local' || arg === '--base=') return '';
    if (arg.startsWith('--base=')) return arg.slice('--base='.length);
  }
  return process.env.PUBLIC_BASE_URL ?? DEFAULT_PUBLIC_BASE_URL;
}

async function main(): Promise<void> {
  // config.ts reads the environment at import time, so set it before loading the app.
  const base = parseBase(process.argv.slice(2));
  if (base === '') delete process.env.PUBLIC_BASE_URL;
  else process.env.PUBLIC_BASE_URL = base;

  const { buildApp } = await import('../src/api/app.js');
  const app = await buildApp();
  await app.ready();
  const document = app.swagger();
  const yamlText =
    `# CIDB Tender API — OpenAPI 3.0\n` +
    `# Auto-generated by \`npm run openapi:export\`. Do not edit by hand.\n` +
    `${stringify(document)}`;
  const outPath = join(process.cwd(), 'docs', 'openapi.yaml');
  writeFileSync(outPath, yamlText, 'utf8');
  const servers = ((document as { servers?: Array<{ url: string }> }).servers ?? [])
    .map((server) => server.url)
    .join(', ');
  console.log(`OpenAPI document written to ${outPath} (servers: ${servers || 'none'})`);
  await app.close();
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
