/**
 * Export the OpenAPI document served at /docs to docs/openapi.yaml.
 *
 *   npm run openapi:export
 *
 * Requires DATABASE_URL to be set (the app validates env on boot) but does
 * not need a live database connection.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { stringify } from 'yaml';
import { buildApp } from '../src/api/app.js';

async function main(): Promise<void> {
  const app = await buildApp();
  await app.ready();
  const document = app.swagger();
  const yamlText = `# CIDB Tender API — OpenAPI 3.0\n# Auto-generated by \`npm run openapi:export\`. Do not edit by hand.\n${stringify(document)}`;
  const outPath = join(process.cwd(), 'docs', 'openapi.yaml');
  writeFileSync(outPath, yamlText, 'utf8');
  console.log(`OpenAPI document written to ${outPath}`);
  await app.close();
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
